apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deplyment
spec:
  selector:
    matchLabels:
      app: test-php
  replicas: 1
  template:
    metadata:
      labels:
        app: test-php
    spec:
      containers:
        - name: angular-front
          image: malekzahmoul20971/cicd-stage:1.0.0-38
          ports:
            - containerPort: 8000


