apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deplyment
spec:
  selector:
    matchLabels:
      app: test-php
  replicas: 1
  template:
    metadata:
      labels:
        app: test-php
    spec:
      containers:
        - name: angular-front
          image: malekzahmoul20971/cicd-stage:1.0.0-34
          ports:
            - containerPort: 8000

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: test-service
spec:
  selector:
    app: test-php
  ports:
    - protocol: "TCP"
      port: 8000 # The port that the service is running on in the cluster
      targetPort: 8000 # The port exposed by the service
  type: LoadBalancer # type of the service.