apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  selector:
    matchLabels:
      app: test-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
        - name: angular-front
          image: malekzahmoul20971/cicd-stage:1.0.0-55
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: test-deployment
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 8000
      nodePort: 30001

